# The URL the site will be built for
base_url = "https://bast.fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "cheerfully-light"


[extra]

navigation = [
  { name = "Home", path = "/" },
  { name = "About", path = "/about/" },
  { name = "Projects", path = "/projects/" },
  { name = "Publications", path = "/publications/" },
  { name = "Blog", path = "/blog/" },
  { name = "Bookmarks", path = "/bookmarks/" }
]

twitter_image = "https://bast.fr/img/avatar.jpg"

about = """
I am a theoretical chemist turned research software engineer.

I write research software and teach programming to researchers and lead the
[CodeRefinery](https://coderefinery.org) project. I am co-creating
the weekly [Research Software Hour](https://researchsoftwarehour.github.io/) stream
and am involved in building the community of
[Nordic research software engineers](https://nordic-rse.org/).

I work at the High Performance Computing Group,
[UiT The Arctic University of Norway](https://uit.no) and
[the Norwegian e-infrastructure for research and education](https://www.nris.no).

I've also worked at the
[Laboratoire de Chimie et Physique Quantiques](http://www.lcpq.ups-tlse.fr/?lang=en) in Toulouse,
and
[PDC](https://www.pdc.kth.se)
and
[Theoretical Chemistry and Biology](https://www.theochem.kth.se) in Stockholm.

[Email](mailto:firstname.lastname@uit.no),
<a rel="me" href="https://fosstodon.org/@radovan">Mastodon</a>,
[Bluesky](https://bsky.app/profile/radovan.bsky.social),
[GitHub](https://github.com/bast),
[GitLab](https://gitlab.com/bast)
"""
